
package com.micmiu.tutorial.webservice.jaxws.client.helloservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://services.jaxws.webservice.tutorial.micmiu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://services.jaxws.webservice.tutorial.micmiu.com/", className = "com.micmiu.tutorial.webservice.jaxws.client.helloservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://services.jaxws.webservice.tutorial.micmiu.com/", className = "com.micmiu.tutorial.webservice.jaxws.client.helloservice.SayHelloResponse")
    public String sayHello(
			@WebParam(name = "userName", targetNamespace = "")
			String userName);

    /**
     * 
     * @param author
     * @return
     *     returns java.util.List<com.micmiu.tutorial.webservice.jaxws.client.helloservice.Blog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryBlog", targetNamespace = "http://services.jaxws.webservice.tutorial.micmiu.com/", className = "com.micmiu.tutorial.webservice.jaxws.client.helloservice.QueryBlog")
    @ResponseWrapper(localName = "queryBlogResponse", targetNamespace = "http://services.jaxws.webservice.tutorial.micmiu.com/", className = "com.micmiu.tutorial.webservice.jaxws.client.helloservice.QueryBlogResponse")
    public List<Blog> queryBlog(
			@WebParam(name = "author", targetNamespace = "")
			String author);

    /**
     * 
     * @param blogList
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBlogList", targetNamespace = "http://services.jaxws.webservice.tutorial.micmiu.com/", className = "com.micmiu.tutorial.webservice.jaxws.client.helloservice.CreateBlogList")
    @ResponseWrapper(localName = "createBlogListResponse", targetNamespace = "http://services.jaxws.webservice.tutorial.micmiu.com/", className = "com.micmiu.tutorial.webservice.jaxws.client.helloservice.CreateBlogListResponse")
    public String createBlogList(
			@WebParam(name = "blogList", targetNamespace = "")
			List<Blog> blogList);

}
